# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr = np.arange(10)
arr.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [8]:
arr = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr1 = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack((arr,arr1))



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:
arr = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr1 = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((arr,arr1))


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [13]:
arr = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr.flatten()


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [17]:
 arr1 =np.random.randn(20).reshape(2,2,5)
arr1.flatten()

array([ 0.3223302 , -0.32711346,  0.29254414,  1.02926046,  0.45331774,
       -0.82589687, -0.80650331, -2.28329821, -0.50285664, -0.2474033 ,
       -2.20380034, -1.90578771, -1.5290791 ,  0.35952241, -0.81342076,
        1.99620577, -3.2982576 ,  2.43934976,  0.52673501, -0.72232551])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [21]:
arr = np.arange(15)
arr.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [24]:
arr_2=np.arange(25).reshape(5,5)
np.square(arr_2)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [28]:
arr_2=np.arange(30).reshape(5,6)
np.mean(arr_2)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [29]:
arr_2=np.arange(30).reshape(5,6)
np.std(arr_2)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [30]:
arr_2=np.arange(30).reshape(5,6)
np.median(arr_2)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [31]:
arr_2=np.arange(30).reshape(5,6)
arr_2.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [35]:
diag = np.arange(16).reshape(4,4)
np.diagonal(diag).sum()

30

## Question:13

### Find the determinant of the previous array in Q12?

In [37]:
diag = np.arange(16).reshape(4,4)
deteminat = np.linalg.det(diag)
print(int(deteminat))

0


## Question:14

### Find the 5th and 95th percentile of an array?

In [41]:
diag = np.arange(100)
fifth=np.percentile(diag ,5)
nighty_fifth=np.percentile(diag ,95)
print(fifth)
print(nighty_fifth)

4.95
94.05


## Question:15

### How to find if a given array has any null values?

In [46]:
diag = np.arange(100)
np.isnan(diag)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])